### ISSUE TITLE
Can I use another transformer based model to train?

### ISSUE THREAD

**Issue by collin0825** [lasigeBioTM/K-RET#2]
Can I use another transformer based model to train like roberta

**Comment by dpavot** [comment]
Yes! You need to follow these steps thought:

1. Download the model of interest (transformer-based) to K-RET/models/ 
2. Then, from the K-RET/uer/  directory, you can run python3 convert_bert_from_huggingface_to_uer.py --input_model_path ../models/[pre_trained_model_scibert/scibert_scivocab_uncased/pytorch_model.bin] --output_model_path ../models/[pre_trained_model_scibert/output_model.bin]  replacing the information within the brackets for what suits you model

**Comment by collin0825** [comment]
should I change config file to correspond model

**Comment by dpavot** [comment]
You can change the token tags for RoBERTa's, but I am unsure how that reflects on the pipeline's behaviour, so if you do it, please leave feedback here.
