### ISSUE TITLE
Cannot use the code you provide to convert roberta

### ISSUE THREAD

**Issue by collin0825** [lasigeBioTM/K-RET#3]
Cannot use the code you provide to convert roberta
the following error will happen
Traceback (most recent call last):
  File "convert_bert_from_huggingface_to_uer.py", line 73, in <module>
    main()
  File "convert_bert_from_huggingface_to_uer.py", line 49, in main
    output_model["embedding.word_embedding.weight"] = input_model["bert.embeddings.word_embeddings.weight"]
KeyError: 'bert.embeddings.word_embeddings.weight'

**Comment by dpavot** [comment]
You need to change the _convert_bert_from_huggingface_to_uer.py_ file on your side. When you have **bert**.embeddings.word_embeddings.weight, for instance, you should replace it by **roberta**.embeddings.word_embeddings.weight, but for all the cases where bert is mentioned.
