### ISSUE TITLE
If I use Roberta which vocab file should I use?

### ISSUE THREAD

**Issue by collin0825** [lasigeBioTM/K-RET#4]
If I use Roberta which vocab file should I use? Roberta have vocab.json and merges.txt. The original code use vocab.txt. Thanks

**Comment by dpavot** [comment]
I'm not sure you can use different file types to do it, assuming it doesn't work implicitly, I would try altering the function that uses those files to handle different file types. There seems to be some online resources discussing it too: 
https://stackoverflow.com/questions/70255025/adding-new-tokens-to-bert-roberta-while-retaining-tokenization-of-adjacent-token
